export const ACCESS_TOKEN_NAME = 'QWEUIOKJKJKKKMMNMNMNMNMASDFG';
export const USER_INFO_CACHE_NAME = 'LOPOOKLMNMNMNMNMNASASASASERTYTY';

const DEFAULT_EXPORT = {
  ACCESS_TOKEN_NAME,
  USER_INFO_CACHE_NAME,
};

export default DEFAULT_EXPORT;
